// <auto-generated />
using System;
using DevLearningPlannerAndTracker.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevLearningPlannerAndTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261008051809_Migrations")]
    partial class Migrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevLearningPlannerAndTracker.Entities.Concepts", b =>
                {
                    b.Property<string>("ConceptId")
                        .HasColumnType("text");

                    b.Property<string>("ConceptName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.HasKey("ConceptId");

                    b.HasIndex("TopicId", "ModuleCode");

                    b.ToTable("concepts");
                });

            modelBuilder.Entity("DevLearningPlannerAndTracker.Entities.Modules", b =>
                {
                    b.Property<string>("ModuleCode")
                        .HasColumnType("text");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ModuleCode");

                    b.ToTable("modules");
                });

            modelBuilder.Entity("DevLearningPlannerAndTracker.Entities.Topics", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("text");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TopicId", "ModuleCode");

                    b.HasIndex("ModuleCode");

                    b.ToTable("topics");
                });

            modelBuilder.Entity("DevLearningPlannerAndTracker.Entities.UserTasks", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<string>("ConceptId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Username", "ConceptId");

                    b.HasIndex("ConceptId");

                    b.ToTable("userTasks");
                });

            modelBuilder.Entity("DevLearningPlannerAndTracker.Entities.Users", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("DevLearningPlannerAndTracker.Entities.Concepts", b =>
                {
                    b.HasOne("DevLearningPlannerAndTracker.Entities.Topics", "conceptTopic")
                        .WithMany("topicConcepts")
                        .HasForeignKey("TopicId", "ModuleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("conceptTopic");
                });

            modelBuilder.Entity("DevLearningPlannerAndTracker.Entities.Topics", b =>
                {
                    b.HasOne("DevLearningPlannerAndTracker.Entities.Modules", "topicModule")
                        .WithMany("moduleTopics")
                        .HasForeignKey("ModuleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("topicModule");
                });

            modelBuilder.Entity("DevLearningPlannerAndTracker.Entities.UserTasks", b =>
                {
                    b.HasOne("DevLearningPlannerAndTracker.Entities.Concepts", "concept")
                        .WithMany("conceptTasks")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevLearningPlannerAndTracker.Entities.Users", "user")
                        .WithMany("userTasks")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("concept");

                    b.Navigation("user");
                });

            modelBuilder.Entity("DevLearningPlannerAndTracker.Entities.Concepts", b =>
                {
                    b.Navigation("conceptTasks");
                });

            modelBuilder.Entity("DevLearningPlannerAndTracker.Entities.Modules", b =>
                {
                    b.Navigation("moduleTopics");
                });

            modelBuilder.Entity("DevLearningPlannerAndTracker.Entities.Topics", b =>
                {
                    b.Navigation("topicConcepts");
                });

            modelBuilder.Entity("DevLearningPlannerAndTracker.Entities.Users", b =>
                {
                    b.Navigation("userTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
